### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by alphaleadership** [StudioDEVIOO/template-portfolio#1]
c'est du php

**Comment by dev-cetus** [comment]
Bonjour,
Oui en effet car le php sert à afficher l'année dans le footer pour le copyright.

Cetus

**Comment by alphaleadership** [comment]
donc le index .html non

**Comment by dev-cetus** [comment]
Ou vois-tu index.html ?

**Comment by Aigle-Noir123** [comment]
> c'est du php

Bonjour ! nous avons changé l'extension du fichier. C'est maintenant .html pour faciliter la compréhension et l'utilisation,


--

Aigle Noir
